// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_QqZ-8KHLkuxSFDw88v3_sEZcQ-hNRsE',
    appId: '1:815507514637:web:f4d3870aff32302671bc44',
    messagingSenderId: '815507514637',
    projectId: 'phroneo-9f732',
    authDomain: 'phroneo-9f732.firebaseapp.com',
    storageBucket: 'phroneo-9f732.firebasestorage.app',
    measurementId: 'G-MH2Z0GBTZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLr8Z_PFmgviVY9R_uppyfa7n0fZUfFII',
    appId: '1:815507514637:android:e80b8698dc706ba171bc44',
    messagingSenderId: '815507514637',
    projectId: 'phroneo-9f732',
    storageBucket: 'phroneo-9f732.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi6q9ImzOE8rQSeKFaZs8e7-cOGLahpHs',
    appId: '1:815507514637:ios:f6dbc932b0e7024d71bc44',
    messagingSenderId: '815507514637',
    projectId: 'phroneo-9f732',
    storageBucket: 'phroneo-9f732.firebasestorage.app',
    iosClientId: '815507514637-8r31g489m8sr6mr5mmcp19pldl8pokh2.apps.googleusercontent.com',
    iosBundleId: 'com.gabrielgoldas.phroneo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi6q9ImzOE8rQSeKFaZs8e7-cOGLahpHs',
    appId: '1:815507514637:ios:f6dbc932b0e7024d71bc44',
    messagingSenderId: '815507514637',
    projectId: 'phroneo-9f732',
    storageBucket: 'phroneo-9f732.firebasestorage.app',
    iosClientId: '815507514637-8r31g489m8sr6mr5mmcp19pldl8pokh2.apps.googleusercontent.com',
    iosBundleId: 'com.gabrielgoldas.phroneo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_QqZ-8KHLkuxSFDw88v3_sEZcQ-hNRsE',
    appId: '1:815507514637:web:d4c7c85d7349e98371bc44',
    messagingSenderId: '815507514637',
    projectId: 'phroneo-9f732',
    authDomain: 'phroneo-9f732.firebaseapp.com',
    storageBucket: 'phroneo-9f732.firebasestorage.app',
    measurementId: 'G-98KL2XXNVC',
  );
}
